version: "3.3"

networks:
  test:

services:
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    image: postgres
    container_name: keycloak-postgres
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - test

